#!/usr/bin/env python3
"""
ForestGump command-line interface wrapper.
This script allows running `python forestgump [commands]` or `./forestgump [commands]`
"""

import sys
from cli import main

if __name__ == '__main__':
    sys.exit(main())
